const pokeType = {
  grass: 'Grass',
  poison: 'Poison',
  bug: 'Bug',
  electric: 'Electric',
  dragon: 'Dragon',
  fighting: 'Fighting',
  fire: 'Fire',
  flying: 'Flying',
  ghost: 'Ghost',
  ground: 'Ground',
  ice: 'Ice',
  normal: 'Normal',
  psychic: 'Psychic',
  rock: 'Rock',
  water: 'Water',
};
export const pokemonsFirstGen = [
  {
    name: 'Bulbasaur',
    type: [pokeType.grass, pokeType.poison],
    imageURL: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/001.png',
    pokedexId: 1,
  },
  {
    name: 'Ivysaur',
    type: [pokeType.grass, pokeType.poison],
    imageURL: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/002.png',
    pokedexId: 2,
  },
  {
    name: 'Venusaur',
    type: [pokeType.grass, pokeType.poison],
    imageURL: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/003.png',
    pokedexId: 3,
  },
  {
    name: 'Charmander ',
    type: [pokeType.fire],
    imageURL: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/004.png',
    pokedexId: 4,
  },
  {
    name: 'Charmeleon ',
    type: [pokeType.fire],
    imageURL: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/005.png',
    pokedexId: 5,
  },
  {
    name: 'Charizard ',
    type: [pokeType.fire, pokeType.flying],
    imageURL: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/006.png',
    pokedexId: 6,
  },
  {
    name: 'Squirtle ',
    type: [pokeType.water],
    imageURL: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/007.png',
    pokedexId: 7,
  },
  {
    name: 'Wartortle ',
    type: [pokeType.water],
    imageURL: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/008.png',
    pokedexId: 8,
  },
  {
    name: 'Blastoise ',
    type: [pokeType.water],
    imageURL: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/009.png',
    pokedexId: 9,
  },
  {
    name: 'Caterpie ',
    type: [pokeType.bug],
    imageURL: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/010.png',
    pokedexId: 10,
  },
  {
    name: 'Metapod ',
    type: [pokeType.bug],
    imageURL: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/011.png',
    pokedexId: 11,
  },
  {
    name: 'Butterfree ',
    type: [pokeType.bug, pokeType.flying],
    imageURL: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/012.png',
    pokedexId: 12,
  },
  {
    name: 'Weedle ',
    type: [pokeType.bug, pokeType.poison],
    imageURL: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/013.png',
    pokedexId: 13,
  },
  {
    name: 'Kakuna ',
    type: [pokeType.bug, pokeType.poison],
    imageURL: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/014.png',
    pokedexId: 14,
  },
  {
    name: 'Beedrill ',
    type: [pokeType.bug, pokeType.poison],
    imageURL: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/015.png',
    pokedexId: 15,
  },
  {
    name: 'Pidgey ',
    type: [pokeType.normal, pokeType.flying],
    imageURL: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/016.png',
    pokedexId: 16,
  },
  {
    name: 'Pidgeotto ',
    type: [pokeType.normal, pokeType.flying],
    imageURL: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/017.png',
    pokedexId: 17,
  },
  {
    name: 'Pidgeot ',
    type: [pokeType.normal, pokeType.flying],
    imageURL: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/018.png',
    pokedexId: 18,
  },
  {
    name: 'Rattata ',
    type: [pokeType.normal],
    imageURL: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/019.png',
    pokedexId: 19,
  },
  {
    name: 'Raticate ',
    type: [pokeType.normal],
    imageURL: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/020.png',
    pokedexId: 20,
  },
  {
    name: 'Spearow ',
    type: [pokeType.normal, pokeType.flying],
    imageURL: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/021.png',
    pokedexId: 21,
  },
  {
    name: 'Fearow ',
    type: [pokeType.normal, pokeType.flying],
    imageURL: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/022.png',
    pokedexId: 22,
  },
  {
    name: 'Ekans ',
    type: [pokeType.poison],
    imageURL: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/023.png',
    pokedexId: 23,
  },
  {
    name: 'Arbok ',
    type: [pokeType.poison],
    imageURL: 'https://assets.pokemon.com/assets/cms2/img/pokedex/full/024.png',
    pokedexId: 24,
  },
];
